version: 0.2

env:
  variables:
    REPO_URI: "991105135696.dkr.ecr.eu-west-1.amazonaws.com/my-lambda-container"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin $REPO_URI
  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPO_URI:latest .
      - docker push $REPO_URI:latest
  post_build:
    commands:
      - echo Updating Lambda function...
      - IMAGE_URI="991105135696.dkr.ecr.eu-west-1.amazonaws.com/my-lambda-container:latest"
      - aws lambda update-function-code --function-name my-container-lambda --image-uri $IMAGE_URI
